pipeline {
    agent {
        node {
                label "ansible-master"  
            }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/dev']], extensions: [], userRemoteConfigs: [[credentialsId: '849445ba-9f7b-48d9-a16c-554b1d1d3aaf', url: 'https://github.com/msethi006/DevOpsProjects.git']]])
            }
        }
        stage('Build using Ansible') {
            steps {
                git credentialsId: '849445ba-9f7b-48d9-a16c-554b1d1d3aaf', url: 'https://github.com/msethi006/DevOpsProjects.git', branch: 'dev'
                ansiblePlaybook disableHostKeyChecking: true, installation: 'ansible-master', inventory: '/etc/ansible/hosts', playbook: './Project3/demo.yml'
            }
        }
        stage('Test') {
            steps {
                echo "Job test"
            }
        }
        }
    }
