pipeline {
    agent {
        node {
                label "test-server"  
            }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: '849445ba-9f7b-48d9-a16c-554b1d1d3aaf', url: 'https://github.com/msethi006/DevOpsProjects.git']]])
            }
        }
        stage('Build') {
            steps {
                git credentialsId: '849445ba-9f7b-48d9-a16c-554b1d1d3aaf', url: 'https://github.com/msethi006/DevOpsProjects.git'
                sh 'docker build -t webapp1 -f ./Project1/Dockerfile .'
                sh 'docker run -d -p 8501:8501 webapp1'
            }
        }
        stage('Test') {
            steps {
                echo "Job test"
            }
        }
        }
    }