pipeline {
    agent {
        node {
                label "test-server"  
            }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'dev']], extensions: [], userRemoteConfigs: [[credentialsId: 'fc83ce96-1eae-481f-a724-e3405a698a03', url: 'https://github.com/msethi006/DevOpsProjects.git']]])
            }
        }
        stage('Build') {
            steps {
                git credentialsId: '849445ba-9f7b-48d9-a16c-554b1d1d3aaf', url: 'https://github.com/msethi006/DevOpsProjects.git' , branch: 'dev'
                sh 'docker stop $(docker ps -a -q)'
                sh 'docker rm $(docker ps -a -q)'
                sh 'docker build -t webapp1 -f ./Project2/Dockerfile .'
                sh 'docker run -d -p 8501:8501 webapp1'
            }
        }
        stage('Test') {
            steps {
                sh 'docker build -t testwebapp1 -f ./Project2/Dockerfile2 .'
                sh 'docker run -dt testwebapp1'
                sh 'docker logs testwebapp1'
            }
        }
        }
    }